MohammedBassem.G01.PL/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MohammedBassem.G01.BLL.interfaces;
using MohammedBassem.G01.DAL.Models;

namespace MohammedBassem.G01.PL.Controllers
{
	[Authorize]
	public class DepartmentController : Controller
    {

        private readonly IDepartmentRepository _departmentRepository; //NULL --> GetAll دي عشان اجيب منها الميثود اللي اسمها property انا عملت ال

        public DepartmentController(IDepartmentRepository departmentRepository) // ASK CLR To Create Object From DepartmentRepository
        {
            _departmentRepository = departmentRepository;
        }




        //Data base مع ال connection فلازم افتح Data base ده هعرض فيه كل حاجه موجوده في ال view ال
        public async Task<IActionResult> Index()
        {
            var department = await _departmentRepository.GetAllAsync();
            return View(department);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Department model)
        {
            if (ModelState.IsValid)
            {
                var count = await _departmentRepository.AddAsync(model);
                if (count > 0)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
            {
                return BadRequest();
            }
            var department = await _departmentRepository.GetAsync(id.Value);
            if (department is null) return NotFound();
            return View(ViewName, department);

        }

        public async Task<IActionResult> Edit(int? id)
        {
            //    if (id is null)
            //    {
            //        return BadRequest();
            //    }
            //    var department = _departmentRepository.Get(id.Value);
            //    if (department is null) return NotFound();
            //    return View(department);

            ////////////////
            ///(Refactoring in Code) دي بدل الكود ده كله
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //Request بتمنع ان اي حد من برا يبعت 
        public async Task<IActionResult> Edit([FromRoute] int? id, Department department)
        {
            try
            {
                if (id != department.Id) return BadRequest();

                if (ModelState.IsValid)
                {
                    var count = await _departmentRepository.UpdateAsync(department);
                    if (count > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(department);

        }

        public async Task<IActionResult> Delete(int? id)
        {
            //if (id is null)
            //{
            //    return BadRequest();
            //}
            //var department = _departmentRepository.Get(id.Value);
            //if (department is null) return NotFound();
            //return View(department);

            ////////////////////
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Department department)
        {
            try
            {
                await _departmentRepository.DeleteAsync(department);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);

                return View(department);
            }

        }
    }
}

MohammedBassem.G01.PL/Controllers/RoleController.cs
 using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using MohammedBassem.G01.DAL.Models;
using MohammedBassem.G01.PL.ViewModels;

namespace MohammedBassem.G01.PL.Controllers
{
    //[Authorize (Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        //Get , GetAll , Create , Update  ,Delete


        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }



        public async Task<IActionResult> Index(string InputSearch)
        {
            var roles = Enumerable.Empty<RoleViewModel>();
            if (InputSearch.IsNullOrEmpty())
            {
                roles = await roleManager.Roles.Select(u => new RoleViewModel()
                {   //Mapping from user to uservm

                    Id = u.Id,
                    RoleName = u.Name

                }).ToListAsync();
            }
            else
            {
                roles = await roleManager.Roles.Where(u => u.Name.
                                                ToLower().
                                                Contains(InputSearch.ToLower()))
                                                .Select(u => new RoleViewModel()
                                                {   //Mapping from user to uservm

                                                    Id = u.Id,
                                                    RoleName = u.Name

                                                }).ToListAsync();
            }

            return View(roles);
        }



        //-----------------------------------------------------------Details-----------------------------------------


        [HttpGet]
        public async Task<IActionResult> Details(string id, string ViewName = "Details")
        {

            if (id is null)
                return BadRequest();

            var roleFromDb = await roleManager.FindByIdAsync(id);

            if (roleFromDb is not null)
            {

                var role = new RoleViewModel()
                {
                    Id = roleFromDb.Id,
                    RoleName = roleFromDb.Name

                };

                return View(ViewName, role);
            }
            return NotFound();
        }



        //----------------------------------------------------------Create----------------------------------------------------


        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Create(RoleViewModel roleVM)
        {
            if (ModelState.IsValid)       //تعمل تاكيد علي الداتا الي رجعالي صح ولا لا
            {
                var role = new IdentityRole()
                {
                    Name = roleVM.RoleName,
                    NormalizedName = roleVM.RoleName.ToUpper()
                };
                var result = await roleManager.CreateAsync(role);
                if (result.Succeeded)
                    return RedirectToAction(nameof(Index));
                ModelState.AddModelError("", "Invalid Role");
            }
            return View(roleVM);
        }



        //--------------------------------------------------------Edit------------------------------------------------

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            return await Details(id, "Edit");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel roleVM)
        {
            if (id != roleVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {

                var roleFromDb = await roleManager.FindByIdAsync(id);

                if (roleFromDb is not null)
                {
                    roleFromDb.Name = roleVM.RoleName;

                    await roleManager.UpdateAsync(roleFromDb);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(roleVM);
        }






        //---------------------------------------------------Delete------------------------------------------------

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }




        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Delete([FromRoute] string id, RoleViewModel roleVM)
        {

            if (id != roleVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {

                var roleFromDb = await roleManager.FindByIdAsync(id);

                if (roleFromDb is not null)
                {
                    await roleManager.DeleteAsync(roleFromDb);
                    return RedirectToAction(nameof(Index));
                }
                return NotFound();
            }
            return View(roleVM);

        }




        //----------------------------------------------------Add Or Remove User From Role----------------------------------------
        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUser(string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            ViewData["RoleId"] = role.Id;
            var UsersInRole = new List<UsersInRoleViewModel>();
            var users = userManager.Users.ToList();
            foreach (var user in users)
            {
                var userInRole = new UsersInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelect = true;
                }
                else
                {
                    userInRole.IsSelect = false;
                }
                UsersInRole.Add(userInRole);
            }
            return View(UsersInRole);



        }


        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUser(string roleId, List<UsersInRoleViewModel> userInRoleVMs)
        {
            var role = await roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in userInRoleVMs)
                {
                    var appUser = await userManager.FindByIdAsync(user.UserId);
                    if (appUser != null)
                    {
                        if (user.IsSelect && !await userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            //Create
                            await userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else if (!user.IsSelect && await userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            //Remove
                            await userManager.RemoveFromRoleAsync(appUser, role.Name);

                        }

                    }

                }
                return RedirectToAction(nameof(Edit), new { id = roleId });

            }
            return View(userInRoleVMs);


        }
    }
}

MohammedBassem.G01.PL/Views/Shared/_AuthLayout1.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib @ViewData["Title"] Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/Auth.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative  @ViewData["Title"] Form</h1>

		@RenderBody()


		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

MohammedBassem.G01.PL/Views/Shared/_ButtonPartialView.cshtml
@model string
<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">Details</a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">Update</a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">Delete</a>
</td>

MohammedBassem.G01.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MohammedBassem.G01.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MohammedBassem.G01.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MohammedBassem.G01.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark  " asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">Log Out</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" >
            &copy; 2024 - MohammedBassem.G01.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Validationsection", required: false)
</body>
</html>